### ISSUE TITLE
`stack setup` fails

### ISSUE THREAD

**Issue by FranklinChen** [jonathanknowles/haskell-calculator#2]
I'm on macOS Sierra, if it matters

```
$ stack setup
...
  --  While building package ghci-8.0.1 using:
      /Users/chen/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/chen/.stack/programs/x86_64-osx/ghcjs-0.2.1.9007001_ghc-8.0.1/src/.stack-work/logs/ghci-8.0.1.log

    Configuring ghci-8.0.1...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package ghc-boot-8.0.1 requires ghc-boot-th-8.0.1
    package template-haskell-2.11.1.0 requires ghc-boot-th-8.0.2
    Building ghci-8.0.1...
    Preprocessing library ghci-8.0.1...
    [ 1 of 13] Compiling SizedSeq         ( SizedSeq.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/SizedSeq.o )
    [ 2 of 13] Compiling GHCi.TH.Binary   ( GHCi/TH/Binary.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/TH/Binary.o )
    [ 3 of 13] Compiling GHCi.Signals     ( GHCi/Signals.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/Signals.o )
    [ 4 of 13] Compiling GHCi.RemoteTypes ( GHCi/RemoteTypes.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/RemoteTypes.o )
    [ 5 of 13] Compiling GHCi.ObjLink     ( GHCi/ObjLink.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/ObjLink.o )
    [ 6 of 13] Compiling GHCi.InfoTable   ( .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/InfoTable.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/InfoTable.o )
    [ 7 of 13] Compiling GHCi.FFI         ( .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/FFI.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/FFI.o )
    [ 8 of 13] Compiling GHCi.BreakArray  ( GHCi/BreakArray.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/BreakArray.o )
    [ 9 of 13] Compiling GHCi.Message     ( GHCi/Message.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/Message.o )
    [10 of 13] Compiling GHCi.TH          ( GHCi/TH.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GHCi/TH.o )

    /private/var/folders/xz/z3wrll111zn03hdhkd_pxs5w0000gp/T/stack37990/ghci-8.0.1/GHCi/TH.hs:127:42: error:
        • Couldn't match expected type ‘ghc-boot-th-8.0.1:GHC.LanguageExtensions.Type.Extension’
                      with actual type ‘TH.Extension’
          NB: ‘TH.Extension’
                is defined in ‘GHC.LanguageExtensions.Type’
                    in package ‘ghc-boot-th-8.0.2’
              ‘ghc-boot-th-8.0.1:GHC.LanguageExtensions.Type.Extension’
                is defined in ‘GHC.LanguageExtensions.Type’
                    in package ‘ghc-boot-th-8.0.1’
        • In the first argument of ‘IsExtEnabled’, namely ‘x’
          In the first argument of ‘ghcCmd’, namely ‘(IsExtEnabled x)’
          In the expression: ghcCmd (IsExtEnabled x)
```

**Comment by jonathanknowles** [comment]
Hi Franklin

Thanks for your bug report. Sorry for the delay in getting back to you.

The output of your invocation of `stack setup` seems a bit unusual. The first thing that caught my eye is that stack seems to be attempting to perform a build with GHC version 8.0.2:
```
  --  While building package ghci-8.0.1 using:
      /Users/chen/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
```
The second piece of evidence is that stack believes there is a dependency on `template-haskell-2.11.1.0`: 
```
    package ghc-boot-8.0.1 requires ghc-boot-th-8.0.1
    package template-haskell-2.11.1.0 requires ghc-boot-th-8.0.2
```
The package `template-haskell-2.11.1.0` is indeed bundled with GHC 8.0.2. It's included as part of the stack LTS 8.* series.

But at the time of writing, the [stack.yaml](https://github.com/jonathanknowles/haskell-calculator/blob/master/stack.yaml) file for this project:
1. specifies a GHCJS based on GHC 8.0.1 (ghcjs-0.2.1.9007001_ghc-8.0.1):
2. specifies LTS 7.1, which includes `template-haskell-2.11.0.0`.

Unless I've misinterpreted the output, it seems that stack is attempting to build with GHC 8.0.2 rather than the specified version of GHCJS based on GHC 8.0.1.

Would it be possible to post the output of the following command:
```
ls ~/.stack/setup-exe-cache/*/
```
And from the root of your `haskell-calculator` directory:
```
stack ghc -- --version
stack list-dependencies
```

First thing to try:

1. Remove the `haskell-calculator/.stack-work` directory and try running `stack setup` again.

If it still doesn't work:

2. Temporarily move your `/Users/chen/.stack/` directory to a different location (for example: `/Users/chen/.stack-old`) and try running `stack setup` again from the root of your `haskell-calculator` directory.

Thanks!

**Comment by FranklinChen** [comment]
I apologize for my user error: it turns out that I had a bad global config file in `~/.stack` which I've fixed.

**Comment by jonathanknowles** [comment]
Hi Franklin
No problem! I appreciate that you took the time to report the problem, even if in the end it was solved by a reconfiguration. :+1: 
Feel free to let me know if you run into any other issues, or have any feedback.
Cheers
Jonathan
